# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "social_icons"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-03-27"
  s.description = "Add social media icons to your Rails 3 using CSS sprites or images"
  s.email = [""]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "assets/images/social_icons/aquaticus/IconsPedia.url",
    "assets/images/social_icons/aquaticus/Quaqe9.url",
    "assets/images/social_icons/aquaticus/ReadMe.rtf",
    "assets/images/social_icons/aquaticus/aquaticus.social.png",
    "assets/images/social_icons/aquaticus/png/blogger.png",
    "assets/images/social_icons/aquaticus/png/delicious.png",
    "assets/images/social_icons/aquaticus/png/digg.png",
    "assets/images/social_icons/aquaticus/png/facebook.png",
    "assets/images/social_icons/aquaticus/png/feed.png",
    "assets/images/social_icons/aquaticus/png/flickr.png",
    "assets/images/social_icons/aquaticus/png/friendfeed.png",
    "assets/images/social_icons/aquaticus/png/friendster.png",
    "assets/images/social_icons/aquaticus/png/furl.png",
    "assets/images/social_icons/aquaticus/png/google.png",
    "assets/images/social_icons/aquaticus/png/lastfm.png",
    "assets/images/social_icons/aquaticus/png/linkedin.png",
    "assets/images/social_icons/aquaticus/png/livejournal.png",
    "assets/images/social_icons/aquaticus/png/magnolia.png",
    "assets/images/social_icons/aquaticus/png/mixx.png",
    "assets/images/social_icons/aquaticus/png/myspace.png",
    "assets/images/social_icons/aquaticus/png/netvibes.png",
    "assets/images/social_icons/aquaticus/png/newsvine.png",
    "assets/images/social_icons/aquaticus/png/picasa.png",
    "assets/images/social_icons/aquaticus/png/pownce.png",
    "assets/images/social_icons/aquaticus/png/reddit.png",
    "assets/images/social_icons/aquaticus/png/social_icons_aqua.png",
    "assets/images/social_icons/aquaticus/png/stumbleupon.png",
    "assets/images/social_icons/aquaticus/png/technorati.png",
    "assets/images/social_icons/aquaticus/png/twitter.png",
    "assets/images/social_icons/aquaticus/png/vimeo.png",
    "assets/images/social_icons/aquaticus/png/webshots.png",
    "assets/images/social_icons/aquaticus/png/wordpress.png",
    "assets/images/social_icons/aquaticus/png/yahoo.png",
    "assets/images/social_icons/aquaticus/png/yelp.png",
    "assets/images/social_icons/aquaticus/png/youtube.png",
    "assets/images/social_icons/default/16/Google.png",
    "assets/images/social_icons/default/16/blogger.png",
    "assets/images/social_icons/default/16/delicious.png",
    "assets/images/social_icons/default/16/digg.png",
    "assets/images/social_icons/default/16/ebay.png",
    "assets/images/social_icons/default/16/facebook.png",
    "assets/images/social_icons/default/16/feed.png",
    "assets/images/social_icons/default/16/flickr.png",
    "assets/images/social_icons/default/16/friendfeed.png",
    "assets/images/social_icons/default/16/friendster.png",
    "assets/images/social_icons/default/16/furl.png",
    "assets/images/social_icons/default/16/lastfm.png",
    "assets/images/social_icons/default/16/linkedin.png",
    "assets/images/social_icons/default/16/livejournal.png",
    "assets/images/social_icons/default/16/magnolia.png",
    "assets/images/social_icons/default/16/mixx.png",
    "assets/images/social_icons/default/16/myspace.png",
    "assets/images/social_icons/default/16/netvibes.png",
    "assets/images/social_icons/default/16/newsvine.png",
    "assets/images/social_icons/default/16/picasa.png",
    "assets/images/social_icons/default/16/pownce.png",
    "assets/images/social_icons/default/16/reddit.png",
    "assets/images/social_icons/default/16/social_icons_16.png",
    "assets/images/social_icons/default/16/stumbleupon.png",
    "assets/images/social_icons/default/16/technorati.png",
    "assets/images/social_icons/default/16/twitter.png",
    "assets/images/social_icons/default/16/vimeo.png",
    "assets/images/social_icons/default/16/webshots.png",
    "assets/images/social_icons/default/16/wordpress.png",
    "assets/images/social_icons/default/16/yelp.png",
    "assets/images/social_icons/default/16/youtube.png",
    "assets/images/social_icons/default/20/Google.png",
    "assets/images/social_icons/default/20/blogger.png",
    "assets/images/social_icons/default/20/convert_jpg_to_1024_in_a_dir.sh",
    "assets/images/social_icons/default/20/delicious.png",
    "assets/images/social_icons/default/20/digg.png",
    "assets/images/social_icons/default/20/ebay.png",
    "assets/images/social_icons/default/20/facebook.png",
    "assets/images/social_icons/default/20/feed.png",
    "assets/images/social_icons/default/20/flickr.png",
    "assets/images/social_icons/default/20/friendfeed.png",
    "assets/images/social_icons/default/20/friendster.png",
    "assets/images/social_icons/default/20/furl.png",
    "assets/images/social_icons/default/20/lastfm.png",
    "assets/images/social_icons/default/20/linkedin.png",
    "assets/images/social_icons/default/20/livejournal.png",
    "assets/images/social_icons/default/20/magnolia.png",
    "assets/images/social_icons/default/20/mixx.png",
    "assets/images/social_icons/default/20/myspace.png",
    "assets/images/social_icons/default/20/netvibes.png",
    "assets/images/social_icons/default/20/newsvine.png",
    "assets/images/social_icons/default/20/picasa.png",
    "assets/images/social_icons/default/20/pownce.png",
    "assets/images/social_icons/default/20/reddit.png",
    "assets/images/social_icons/default/20/social_icons_20.png",
    "assets/images/social_icons/default/20/stumbleupon.png",
    "assets/images/social_icons/default/20/technorati.png",
    "assets/images/social_icons/default/20/twitter.png",
    "assets/images/social_icons/default/20/vimeo.png",
    "assets/images/social_icons/default/20/webshots.png",
    "assets/images/social_icons/default/20/wordpress.png",
    "assets/images/social_icons/default/20/yelp.png",
    "assets/images/social_icons/default/20/youtube.png",
    "assets/images/social_icons/default/24/Google.png",
    "assets/images/social_icons/default/24/blogger.png",
    "assets/images/social_icons/default/24/delicious.png",
    "assets/images/social_icons/default/24/digg.png",
    "assets/images/social_icons/default/24/ebay.png",
    "assets/images/social_icons/default/24/facebook.png",
    "assets/images/social_icons/default/24/feed.png",
    "assets/images/social_icons/default/24/flickr.png",
    "assets/images/social_icons/default/24/friendfeed.png",
    "assets/images/social_icons/default/24/friendster.png",
    "assets/images/social_icons/default/24/furl.png",
    "assets/images/social_icons/default/24/lastfm.png",
    "assets/images/social_icons/default/24/linkedin.png",
    "assets/images/social_icons/default/24/livejournal.png",
    "assets/images/social_icons/default/24/magnolia.png",
    "assets/images/social_icons/default/24/mixx.png",
    "assets/images/social_icons/default/24/myspace.png",
    "assets/images/social_icons/default/24/netvibes.png",
    "assets/images/social_icons/default/24/newsvine.png",
    "assets/images/social_icons/default/24/picasa.png",
    "assets/images/social_icons/default/24/pownce.png",
    "assets/images/social_icons/default/24/reddit.png",
    "assets/images/social_icons/default/24/social_icons_24.png",
    "assets/images/social_icons/default/24/stumbleupon.png",
    "assets/images/social_icons/default/24/technorati.png",
    "assets/images/social_icons/default/24/twitter.png",
    "assets/images/social_icons/default/24/vimeo.png",
    "assets/images/social_icons/default/24/webshots.png",
    "assets/images/social_icons/default/24/wordpress.png",
    "assets/images/social_icons/default/24/yelp.png",
    "assets/images/social_icons/default/24/youtube.png",
    "assets/images/social_icons/default/48/Google.png",
    "assets/images/social_icons/default/48/blogger.png",
    "assets/images/social_icons/default/48/delicious.png",
    "assets/images/social_icons/default/48/digg.png",
    "assets/images/social_icons/default/48/ebay.png",
    "assets/images/social_icons/default/48/facebook.png",
    "assets/images/social_icons/default/48/feed.png",
    "assets/images/social_icons/default/48/flickr.png",
    "assets/images/social_icons/default/48/friendfeed.png",
    "assets/images/social_icons/default/48/friendster.png",
    "assets/images/social_icons/default/48/furl.png",
    "assets/images/social_icons/default/48/lastfm.png",
    "assets/images/social_icons/default/48/linkedin.png",
    "assets/images/social_icons/default/48/livejournal.png",
    "assets/images/social_icons/default/48/magnolia.png",
    "assets/images/social_icons/default/48/mixx.png",
    "assets/images/social_icons/default/48/myspace.png",
    "assets/images/social_icons/default/48/netvibes.png",
    "assets/images/social_icons/default/48/newsvine.png",
    "assets/images/social_icons/default/48/picasa.png",
    "assets/images/social_icons/default/48/pownce.png",
    "assets/images/social_icons/default/48/reddit.png",
    "assets/images/social_icons/default/48/social_icons_48.png",
    "assets/images/social_icons/default/48/stumbleupon.png",
    "assets/images/social_icons/default/48/technorati.png",
    "assets/images/social_icons/default/48/twitter.png",
    "assets/images/social_icons/default/48/vimeo.png",
    "assets/images/social_icons/default/48/webshots.png",
    "assets/images/social_icons/default/48/wordpress.png",
    "assets/images/social_icons/default/48/yelp.png",
    "assets/images/social_icons/default/48/youtube.png",
    "assets/images/social_icons/default/60/Google.psd",
    "assets/images/social_icons/default/60/blogger.png",
    "assets/images/social_icons/default/60/delicious.png",
    "assets/images/social_icons/default/60/digg.png",
    "assets/images/social_icons/default/60/ebay.png",
    "assets/images/social_icons/default/60/facebook.png",
    "assets/images/social_icons/default/60/feed.png",
    "assets/images/social_icons/default/60/flickr.png",
    "assets/images/social_icons/default/60/friendfeed.png",
    "assets/images/social_icons/default/60/friendster.png",
    "assets/images/social_icons/default/60/furl.png",
    "assets/images/social_icons/default/60/lastfm.png",
    "assets/images/social_icons/default/60/linkedin.png",
    "assets/images/social_icons/default/60/livejournal.png",
    "assets/images/social_icons/default/60/magnolia.png",
    "assets/images/social_icons/default/60/mixx.png",
    "assets/images/social_icons/default/60/myspace.png",
    "assets/images/social_icons/default/60/netvibes.png",
    "assets/images/social_icons/default/60/newsvine.png",
    "assets/images/social_icons/default/60/picasa.png",
    "assets/images/social_icons/default/60/pownce.png",
    "assets/images/social_icons/default/60/reddit.png",
    "assets/images/social_icons/default/60/social_icons_60.png",
    "assets/images/social_icons/default/60/stumbleupon.png",
    "assets/images/social_icons/default/60/technorati.png",
    "assets/images/social_icons/default/60/twitter.png",
    "assets/images/social_icons/default/60/vimeo.png",
    "assets/images/social_icons/default/60/webshots.png",
    "assets/images/social_icons/default/60/wordpress.png",
    "assets/images/social_icons/default/60/yelp.png",
    "assets/images/social_icons/default/60/youtube.png",
    "assets/images/social_icons/default/readme.txt",
    "assets/stylesheets/social_icons.css",
    "assets/stylesheets/social_icons_aqua.css",
    "assets/stylesheets/social_icons_default_16.css",
    "assets/stylesheets/social_icons_default_20.css",
    "assets/stylesheets/social_icons_default_24.css",
    "assets/stylesheets/social_icons_default_48.css",
    "assets/stylesheets/social_icons_default_60.css",
    "init.rb",
    "install.rb",
    "lib/social_icons.rb",
    "lib/social_icons/rails_engine.rb",
    "lib/social_icons/view_helpers.rb",
    "social_icons.gemspec",
    "test/social_icons_test.rb",
    "test/test_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = "https://github.com/kristianmandrup/social_icons"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.20"
  s.summary = "Social media icons for Rails 3"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 3"])
      s.add_development_dependency(%q<rspec>, [">= 2"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.5"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3"])
      s.add_dependency(%q<rspec>, [">= 2"])
      s.add_dependency(%q<rspec-rails>, [">= 2.5"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3"])
    s.add_dependency(%q<rspec>, [">= 2"])
    s.add_dependency(%q<rspec-rails>, [">= 2.5"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

